---
- name: Deploy CV Docker Container
  hosts: almalinux8_agents
  become: yes

  tasks:
  #  - name: Install Docker
   #   dnf:
    #    name: docker-ce
     #   state: present
      #  update_cache: yes

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create project directory
      file:
        path: ~/zeeshanriaz
        state: directory

    - name: Copy Dockerfile to agent
      copy:
        src: Dockerfile
        dest: ~/zeeshanriaz/Dockerfile

    - name: Copy resume.html to agent
      copy:
        src: resume.html
        dest: ~/zeeshanriaz/resume.html

    - name: Build Docker image
      command: docker build -t zeeshan_image ~/zeeshanriaz

    - name: Run Docker container
      command: docker run -d --name zeeshan-resume -p 84:80 zeeshan_image
